### ISSUE TITLE
HTML5 Geolocation GPS 값을 TM 좌표로 변환하여 대기 측정소 정보 얻어오기

### ISSUE THREAD

**Issue by joshua1988** [joshua1988/DevCampWAP-PWA#9]
# 뭘 구현해야 하는가?
1) HTML5 Geolocation API 로 GPS 좌표 획득
2) 얻은 GPS 좌표를 TM 좌표로 변환
3) TM 좌표로 가까운 대기측정소 정보 확인

## 1. HTML5 Geolocation API 로 현재 GPS 좌표 얻기
**navigator.geolocation.getCurrentPosition()** 를 사용하면 대략,
latitude : 37.4039723
longitude : 127.10263540000001
이정도가 나온다.

## 2. GPS 좌표를 TM 좌표로 변환하기
[다음 좌표계 변환 API](https://developers.daum.net/services/apis/local/geo/transcoord) 를 활용하여 Geolocation 데이터를 TM 좌표로 변환

## 3. TM 좌표로 근접 대기소 정보 찾기
[근접 대기측정소 API](https://www.data.go.kr/subMain.jsp?param=T1BFTkFQSUAxNTAwMDY2MA==#/L3B1YnIvcG90L215cC9Jcm9zTXlQYWdlL29wZW5EZXZHdWlkZVBhZ2UkQF4wMTIkQF5wdWJsaWNEYXRhRGV0YWlsUGs9dWRkaTozMWI4N2JmYi05ZjNjLTQyMTEtYTAzOC1hNDFlMDg3MDgyOGUkQF5tYWluRmxhZz10cnVl) 를 참고하여, 변환한 TM 좌표에 해당하는 근접대기소 정보를 화면에 표시

## Optional
Geolocation 데이터로 현재 위치를 가져오는 [Google Map 표시](https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation_map)도 화면에 표시 가능

## 참고자료
[미세먼지 측정앱 만들기](http://answerofgod.tistory.com/entry/%EB%AF%B8%EC%84%B8%EB%A8%BC%EC%A7%80-%EC%B8%A1%EC%A0%95-%EC%95%B1-%EB%A7%8C%EB%93%A4%EA%B8%B0-5)
[미세먼지 측정앱을 위한 좌표변환](http://answerofgod.tistory.com/entry/%EC%A2%8C%ED%91%9C%EA%B3%84-%EB%B3%80%ED%99%98%ED%95%98%EA%B8%B0#recentComments)

**Comment by joshua1988** [comment]
Found workaround APIs and don't need this step anymore

**Comment by JungSuk-byun** [comment]
let me know how did you solve it?

**Comment by gwnuysw** [comment]
tm 좌표는 왜쓰는 거죠?

**Comment by JungSuk-byun** [comment]
공공데이터에서 대기오염측정소 조회하는 api 인자로 tm좌표를 받네요

2019년 4월 11일 (목) 오전 10:18, seokwon <notifications@github.com>님이 작성:
